package com.example.ecomm;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Login {

    // encrypting the password
    private static byte[] getSha(String input){

        try{
            MessageDigest messageDigest = MessageDigest.getInstance("SHA-256");
            return messageDigest.digest(input.getBytes(StandardCharsets.UTF_8));
        } catch (Exception e){
            e.printStackTrace();
        }
        return  null;
    }

    // now convert this generated byte to normal string to store it
    private static String getEncryptedPassword(String password){

        try{
            BigInteger num = new BigInteger(1,getSha(password));
            StringBuilder hexString = new StringBuilder(num.toString(16));  // converting to string
            return  hexString.toString();
        } catch (Exception exception){
            exception.printStackTrace();
        }

        return  null;
    }

    public  static Customer coustomerLogin(String userEmail, String password)  {

        // created a query
        String encryptedPass = getEncryptedPassword(password);    // got the encryped pass word
        String query = " SELECT * FROM customer WHERE email = '" + userEmail + "' and password = '" + encryptedPass +"'";

        // now to execute the query i need to connect with database
        DatabaseConnection databaseConnection = new DatabaseConnection();

        try{
            ResultSet resultSet = databaseConnection.getQuery(query);    // executing the query using statement,,,,and getting the result of that query

            if(resultSet != null && resultSet.next()){

               return new Customer(resultSet.getInt("cid"),
                        resultSet.getString("name"),
                        resultSet.getString("email")
                      );

            }
        } catch (Exception e){
            e.printStackTrace();
        }

        return null;
    }

//    public static void main(String[] args) {
////        System.out.println(coustomerLogin("kabhay@gmail.com","abhay"));
//        System.out.println(getEncryptedPassword("mohan"));
//    }
}
